spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/price_tracker
    username: postgres
    password: Leesohyun0102$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false